-- Seed tags for programmatic /bdsm-events/{state}/{tag} pages (idempotent)
INSERT INTO public.tags (slug, label, description) VALUES
  ('beginner-friendly', 'Beginner friendly', NULL),
  ('vetted-event', 'Vetted events', NULL),
  ('vetted-events', 'Vetted events', NULL),
  ('lgbtq-friendly', 'LGBTQ+ friendly', NULL),
  ('rope', 'Rope / shibari', NULL),
  ('impact', 'Impact play', NULL),
  ('public', 'Public events', NULL),
  ('private', 'Private events', NULL),
  ('munch', 'Munches', NULL),
  ('play-party', 'Play parties', NULL),
  ('play_party', 'Play parties', NULL),
  ('classes', 'Classes', NULL),
  ('class', 'Classes', NULL),
  ('femdom', 'Femdom', NULL),
  ('bdsm-workshops', 'BDSM workshops', NULL),
  ('private-events', 'Private events', NULL),
  ('public-events', 'Public events', NULL),
  ('fetish-parties', 'Fetish parties', NULL),
  ('dungeon-events', 'Dungeon events', NULL),
  ('bdsm-social', 'BDSM socials', NULL),
  ('newcomer-events', 'Newcomer events', NULL),
  ('advanced-play', 'Advanced play', NULL),
  ('impact-play', 'Impact play', NULL),
  ('rope-jams', 'Rope jams', NULL),
  ('latex-fetish', 'Latex / fetish', NULL),
  ('costume-events', 'Costume events', NULL),
  ('night-events', 'Night events', NULL),
  ('weekend-events', 'Weekend events', NULL),
  ('bdsm-meetups', 'BDSM meetups', NULL),
  ('kink-parties', 'Kink parties', NULL),
  ('community-events', 'Community events', NULL),
  ('convention', 'Conventions', NULL),
  ('social', 'Social events', NULL)
ON CONFLICT (slug) DO UPDATE SET
  label = EXCLUDED.label,
  description = COALESCE(tags.description, EXCLUDED.description);
