export type PalettePreset = {
  id: string
  name: string
  tagline: string
  bestFor: string
  vars: Record<string, string>
}

/** Sample palettes for outdoor / mobile readability review. */
export const PALETTE_PRESETS: PalettePreset[] = [
  {
    id: 'current',
    name: 'Current — Parchment & Brass',
    tagline: 'Live product default',
    bestFor: 'Mobile + outdoor; attendee & organizer',
    vars: {
      '--dc-surface': '#f4f0e8',
      '--dc-surface-muted': '#e8e2d6',
      '--dc-elevated-solid': '#ffffff',
      '--dc-text': '#1c1814',
      '--dc-text-muted': '#4f483f',
      '--dc-muted': '#4f483f',
      '--dc-accent': '#8b6914',
      '--dc-accent-hover': '#6e5310',
      '--dc-accent-muted': '#ede4cf',
      '--dc-accent-border': '#9a7b2f',
      '--dc-accent-foreground': '#ffffff',
      '--dc-border-subtle': '#c9b896',
      '--dc-compare-mutual': '#2f6b4f',
      '--dc-compare-busy': '#b91c1c',
      '--dc-compare-host-only': '#3d5a80',
      '--dc-compare-outside': '#d4cfc4',
    },
  },
  {
    id: 'parchment',
    name: 'Parchment & Brass',
    tagline: 'Warm light — recommended outdoor default',
    bestFor: 'Mobile + daylight; keeps gold brand',
    vars: {
      '--dc-surface': '#f4f0e8',
      '--dc-surface-muted': '#e8e2d6',
      '--dc-elevated-solid': '#ffffff',
      '--dc-text': '#1c1814',
      '--dc-text-muted': '#4f483f',
      '--dc-muted': '#4f483f',
      '--dc-accent': '#8b6914',
      '--dc-accent-hover': '#6e5310',
      '--dc-accent-muted': '#ede4cf',
      '--dc-accent-border': '#9a7b2f',
      '--dc-accent-foreground': '#ffffff',
      '--dc-border-subtle': '#c9b896',
      '--dc-compare-mutual': '#2f6b4f',
      '--dc-compare-busy': '#b91c1c',
      '--dc-compare-host-only': '#3d5a80',
    },
  },
  {
    id: 'noon',
    name: 'High Noon',
    tagline: 'Maximum contrast for sunlight',
    bestFor: 'Gate / hallway / “sunlight mode” toggle',
    vars: {
      '--dc-surface': '#fafaf8',
      '--dc-surface-muted': '#f0f0ee',
      '--dc-elevated-solid': '#ffffff',
      '--dc-text': '#111111',
      '--dc-text-muted': '#444444',
      '--dc-muted': '#444444',
      '--dc-accent': '#b45309',
      '--dc-accent-hover': '#92400e',
      '--dc-accent-muted': '#ffedd5',
      '--dc-accent-border': '#c2410c',
      '--dc-accent-foreground': '#ffffff',
      '--dc-border-subtle': '#999999',
      '--dc-compare-mutual': '#15803d',
      '--dc-compare-busy': '#b91c1c',
      '--dc-compare-host-only': '#1e40af',
    },
  },
  {
    id: 'camp',
    name: 'Camp Day',
    tagline: 'Friendly festival energy',
    bestFor: 'Volunteers, outdoor camp weekends',
    vars: {
      '--dc-surface': '#f7f5f0',
      '--dc-surface-muted': '#ede9e0',
      '--dc-elevated-solid': '#ffffff',
      '--dc-text': '#1a2e1f',
      '--dc-text-muted': '#3d5245',
      '--dc-muted': '#3d5245',
      '--dc-accent': '#9a7b2f',
      '--dc-accent-hover': '#7a6224',
      '--dc-accent-muted': '#e8f0ea',
      '--dc-accent-border': '#7a6224',
      '--dc-accent-foreground': '#ffffff',
      '--dc-border-subtle': '#b8c9b8',
      '--dc-compare-mutual': '#2d6a4f',
      '--dc-compare-busy': '#c2410c',
      '--dc-compare-host-only': '#4a6fa5',
    },
  },
  {
    id: 'slate',
    name: 'Coastal Slate',
    tagline: 'Cool light — organizer crisp',
    bestFor: 'Long console sessions, data-heavy grids',
    vars: {
      '--dc-surface': '#f2f4f6',
      '--dc-surface-muted': '#e4e8ec',
      '--dc-elevated-solid': '#ffffff',
      '--dc-text': '#0f172a',
      '--dc-text-muted': '#475569',
      '--dc-muted': '#475569',
      '--dc-accent': '#b8860b',
      '--dc-accent-hover': '#996f09',
      '--dc-accent-muted': '#fef3c7',
      '--dc-accent-border': '#b8860b',
      '--dc-accent-foreground': '#0f172a',
      '--dc-border-subtle': '#94a3b8',
      '--dc-compare-mutual': '#047857',
      '--dc-compare-busy': '#dc2626',
      '--dc-compare-host-only': '#2563eb',
    },
  },
  {
    id: 'lifted',
    name: 'Lifted Ink',
    tagline: 'Improved dark for night only',
    bestFor: 'After-dark; still not ideal outdoors',
    vars: {
      '--dc-surface': '#1a1816',
      '--dc-surface-muted': '#252220',
      '--dc-elevated-solid': '#2e2b28',
      '--dc-text': '#faf8f5',
      '--dc-text-muted': '#c4bbb0',
      '--dc-muted': '#c4bbb0',
      '--dc-accent': '#e8d5a8',
      '--dc-accent-hover': '#f5ecd4',
      '--dc-accent-muted': 'rgba(232, 213, 168, 0.14)',
      '--dc-accent-border': 'rgba(232, 213, 168, 0.45)',
      '--dc-accent-foreground': '#1a1510',
      '--dc-border-subtle': 'rgba(232, 213, 168, 0.32)',
      '--dc-compare-mutual': '#9cb88a',
      '--dc-compare-busy': '#e8a4a4',
      '--dc-compare-host-only': '#4a6fa5',
    },
  },
]
